export const SET_COLLECTIONS = "SET_COLLECTION";
export const SET_COLLECTION_PRODUCTS = "SET_COLLECTION_PRODUCTS";
export const SET_PRODUCT_LIST = "SET_PRODUCT_LIST";
export const SET_PRODUCT = "SET_PRODUCT";
export const SET_LOADING = "SET_LOADING";
export const SET_ERROR = "SET_ERROR";
