// Collections
export const SET_COLLECTIONS = "SET_COLLECTION";
export const SET_COLLECTION_PRODUCTS = "SET_COLLECTION_PRODUCTS";

// Products
export const SET_PRODUCT_LIST = "SET_PRODUCT_LIST";
export const SET_PRODUCT = "SET_PRODUCT";

export const SET_LOADING = "SET_LOADING";
export const SET_ERROR = "SET_ERROR";

// Cart
export const ADD_TO_CART = "ADD_TO_CART";
export const CLEAR_CART = "CLEAR_CART";
export const SAVE_SHIPPING_ADDRESS = "SAVE_SHIPPING_ADDRESS";
export const SAVE_PAYMENT_METHOD = "SAVE_PAYMENT_METHOD";

// Auth
export const LOGIN = "LOGIN";
export const SIGN_UP = "SIGN_UP";
export const LOGOUT = "LOGOUT";

// Users
export const SET_USER = "SET_USER";
export const CLEAR_USER = "CLEAR_USER";

export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_LOADING = "UPDATE_USER_LOADING";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const UPDATE_PASSWORD = "UPDATE_PASSWORD";
export const UPDATE_PASSWORD_ERROR = "UPDATE_PASSWORD_ERROR";
export const UPDATE_PASSWORD_LOADING = "UPDATE_PASSWORD_LOADING";

export const RESET_USER_STATE = "RESET_USER_STATE";

// Orders
export const CREATE_ORDER = "CREATE_ORDER";
export const SET_ORDER = "SET_ORDER";
export const SET_USER_ORDERS = "SET_USER_ORDERS";

export const ORDER_PAY_LOADING = "ORDER_PAY_LOADING";
export const ORDER_PAY_SUCCESS = "ORDER_PAY_SUCCESS";

export const CREATE_STRIPE_SESSION = "CREATE_STRIPE_SESSION";
